export const pokemonstats = [
  {
    base_stat: 50,
    effort: 0,
    id: 943,
    pokemon_id: 158,
    stat_id: 1,
    pokemon_v2_stat: { name: "hp" },
  },
  {
    base_stat: 65,
    effort: 1,
    id: 944,
    pokemon_id: 158,
    stat_id: 2,
    pokemon_v2_stat: { name: "attack" },
  },
  {
    base_stat: 64,
    effort: 0,
    id: 945,
    pokemon_id: 158,
    stat_id: 3,
    pokemon_v2_stat: { name: "defense" },
  },
  {
    base_stat: 44,
    effort: 0,
    id: 946,
    pokemon_id: 158,
    stat_id: 4,
    pokemon_v2_stat: { name: "special-attack" },
  },
  {
    base_stat: 48,
    effort: 0,
    id: 947,
    pokemon_id: 158,
    stat_id: 5,
    pokemon_v2_stat: { name: "special-defense" },
  },
  {
    base_stat: 43,
    effort: 0,
    id: 948,
    pokemon_id: 158,
    stat_id: 6,
    pokemon_v2_stat: { name: "speed" },
  },
];
