import { GET_EVOLUTIONCHAIN } from "@GraphQL/evolutionchain/queries";
import { SEARCH_POKEMON } from "@GraphQL/pokemon/queries";

export const pokemon = {
  base_experience: 63,
  height: 6,
  id: 158,
  is_default: true,
  name: "totodile",
  order: 255,
  pokemon_species_id: 158,
  pokemon_v2_pokemonforms: [
    {
      form_name: "",
      form_order: 1,
      id: 158,
      is_battle_only: false,
      is_default: true,
      is_mega: false,
      name: "totodile",
      order: 256,
      pokemon_id: 158,
    },
  ],
  weight: 95,
  pokemon_v2_pokemonabilities: [
    {
      ability_id: 67,
      id: 408,
      is_hidden: false,
      pokemon_id: 158,
      pokemon_v2_ability: {
        name: "torrent",
        pokemon_v2_abilityflavortexts: [
          { id: 4291 },
          { id: 4292 },
          { id: 4293 },
          { id: 4294 },
          { id: 4295 },
          { id: 4296 },
          { id: 4297 },
          { id: 4298 },
          { id: 4299 },
          { id: 4300 },
          { id: 4301 },
          { id: 4302 },
          { id: 4303 },
          { id: 4304 },
          { id: 4305 },
          { id: 4306 },
          { id: 4307 },
          { id: 4308 },
          { id: 4309 },
          { id: 4310 },
          { id: 4311 },
          { id: 4312 },
          { id: 4313 },
          { id: 4314 },
          { id: 4315 },
          { id: 4316 },
          { id: 4317 },
          { id: 4318 },
          { id: 4319 },
          { id: 4320 },
          { id: 4321 },
          { id: 4322 },
          { id: 4323 },
          { id: 4324 },
          { id: 4325 },
          { id: 4326 },
          { id: 4327 },
          { id: 4328 },
          { id: 4329 },
          { id: 4330 },
          { id: 4331 },
          { id: 4332 },
          { id: 4333 },
          { id: 4334 },
          { id: 4335 },
          { id: 4336 },
          { id: 4337 },
          { id: 4338 },
          { id: 4339 },
          { id: 4340 },
          { id: 4341 },
          { id: 4342 },
          { id: 4343 },
          { id: 4344 },
          { id: 4345 },
          { id: 4346 },
          { id: 4347 },
          { id: 4348 },
          { id: 4349 },
          { id: 4350 },
          { id: 4351 },
          { id: 4352 },
          { id: 4353 },
          { id: 4354 },
          { id: 4355 },
        ],
      },
    },
    {
      ability_id: 125,
      id: 409,
      is_hidden: true,
      pokemon_id: 158,
      pokemon_v2_ability: {
        name: "sheer-force",
        pokemon_v2_abilityflavortexts: [
          { id: 7914 },
          { id: 7915 },
          { id: 7916 },
          { id: 7917 },
          { id: 7918 },
          { id: 7919 },
          { id: 7920 },
          { id: 7921 },
          { id: 7922 },
          { id: 7923 },
          { id: 7924 },
          { id: 7925 },
          { id: 7926 },
          { id: 7927 },
          { id: 7928 },
          { id: 7929 },
          { id: 7930 },
          { id: 7931 },
          { id: 7932 },
          { id: 7933 },
          { id: 7934 },
          { id: 7935 },
          { id: 7936 },
          { id: 7937 },
          { id: 7938 },
          { id: 7939 },
          { id: 7940 },
          { id: 7941 },
          { id: 7942 },
          { id: 7943 },
          { id: 7944 },
          { id: 7945 },
          { id: 7946 },
          { id: 7947 },
          { id: 7948 },
          { id: 7949 },
          { id: 7950 },
          { id: 7951 },
          { id: 7952 },
          { id: 7953 },
          { id: 7954 },
          { id: 7955 },
          { id: 7956 },
          { id: 7957 },
          { id: 7958 },
          { id: 7959 },
          { id: 7960 },
          { id: 7961 },
          { id: 7962 },
          { id: 7963 },
          { id: 7964 },
          { id: 7965 },
          { id: 7966 },
          { id: 7967 },
          { id: 7968 },
          { id: 7969 },
          { id: 7970 },
          { id: 7971 },
          { id: 7972 },
        ],
      },
    },
  ],
  pokemon_v2_pokemonstats: [
    {
      base_stat: 50,
      effort: 0,
      id: 943,
      pokemon_id: 158,
      stat_id: 1,
      pokemon_v2_stat: { name: "hp" },
    },
    {
      base_stat: 65,
      effort: 1,
      id: 944,
      pokemon_id: 158,
      stat_id: 2,
      pokemon_v2_stat: { name: "attack" },
    },
    {
      base_stat: 64,
      effort: 0,
      id: 945,
      pokemon_id: 158,
      stat_id: 3,
      pokemon_v2_stat: { name: "defense" },
    },
    {
      base_stat: 44,
      effort: 0,
      id: 946,
      pokemon_id: 158,
      stat_id: 4,
      pokemon_v2_stat: {
        name: "special-attack",
      },
    },
    {
      base_stat: 48,
      effort: 0,
      id: 947,
      pokemon_id: 158,
      stat_id: 5,
      pokemon_v2_stat: {
        name: "special-defense",
      },
    },
    {
      base_stat: 43,
      effort: 0,
      id: 948,
      pokemon_id: 158,
      stat_id: 6,
      pokemon_v2_stat: { name: "speed" },
    },
  ],
  pokemon_v2_pokemontypes: [
    {
      pokemon_id: 158,
      pokemon_v2_type: {
        name: "water",
        pokemon_v2_generation: {
          name: "generation-i",
        },
      },
    },
  ],
};

export const pokemonspecies = [
  {
    id: 158,
    pokemon_v2_pokemons: [{ name: "totodile" }],
    pokemon_v2_pokemonspeciesflavortexts: [
      {
        language_id: 9,
        flavor_text:
          "Its well-developed\njaws are powerful\nand capable of\fcrushing anything.\nEven its trainer\nmust be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It is small but\nrough and tough.\nIt won't hesitate\fto take a bite out\nof anything that\nmoves.",
      },
      {
        language_id: 9,
        flavor_text:
          "This rough critter\nchomps at any\nmoving object it\fsees. Turning your\nback on it is not\nrecommended.",
      },
      {
        language_id: 9,
        flavor_text:
          "Despite the smallness of its body,\nTOTODILE’s jaws are very powerful.\nWhile the POKéMON may think it is just\fplayfully nipping, its bite has enough\npower to cause serious injury.",
      },
      {
        language_id: 9,
        flavor_text:
          "Despite the smallness of its body,\nTOTODILE’s jaws are very powerful.\nWhile the POKéMON may think it is just\fplayfully nipping, its bite has enough\npower to cause serious injury.",
      },
      {
        language_id: 9,
        flavor_text:
          "Despite its small body, TOTODILE’s jaws\nare very powerful. While it may think it is\njust playfully nipping, its bite has enough\nstrength to cause serious injury.",
      },
      {
        language_id: 9,
        flavor_text:
          "It is small but rough and tough. It won’t\nhesitate to take a bite out of anything\nthat moves.",
      },
      {
        language_id: 9,
        flavor_text:
          "Its well-developed jaws are powerful and\ncapable of crushing anything. Even its\nTRAINER must be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "Its powerful, well-developed jaws\nare capable of crushing anything.\nEven its Trainer must be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It is small but rough and tough.\nIt won’t hesitate to take a bite out\nof anything that moves.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It has the habit of biting anything\nwith its developed jaws. Even its\nTrainer needs to be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "It is small but rough and tough. It won’t hesitate to\ntake a bite out of anything that moves.",
      },
      {
        language_id: 9,
        flavor_text:
          "Its powerful, well-developed jaws are capable of\ncrushing anything. Even its Trainer must be careful.",
      },
      {
        language_id: 9,
        flavor_text:
          "Despite the smallness of its body, Totodile’s jaws are very\npowerful. While the Pokémon may think it is just playfully\nnipping, its bite has enough power to cause serious injury.",
      },
      {
        language_id: 9,
        flavor_text:
          "Despite the smallness of its body, Totodile’s jaws are very\npowerful. While the Pokémon may think it is just playfully\nnipping, its bite has enough power to cause serious injury.",
      },
    ],
  },
  {
    id: 159,
    pokemon_v2_pokemons: [{ name: "croconaw" }],
    pokemon_v2_pokemonspeciesflavortexts: [],
  },
  {
    id: 160,
    pokemon_v2_pokemons: [{ name: "feraligatr" }],
    pokemon_v2_pokemonspeciesflavortexts: [],
  },
];

export const pokemonstats = [
  {
    base_stat: 50,
    effort: 0,
    id: 943,
    pokemon_id: 158,
    stat_id: 1,
    pokemon_v2_stat: { name: "hp" },
  },
  {
    base_stat: 65,
    effort: 1,
    id: 944,
    pokemon_id: 158,
    stat_id: 2,
    pokemon_v2_stat: { name: "attack" },
  },
  {
    base_stat: 64,
    effort: 0,
    id: 945,
    pokemon_id: 158,
    stat_id: 3,
    pokemon_v2_stat: { name: "defense" },
  },
  {
    base_stat: 44,
    effort: 0,
    id: 946,
    pokemon_id: 158,
    stat_id: 4,
    pokemon_v2_stat: { name: "special-attack" },
  },
  {
    base_stat: 48,
    effort: 0,
    id: 947,
    pokemon_id: 158,
    stat_id: 5,
    pokemon_v2_stat: { name: "special-defense" },
  },
  {
    base_stat: 43,
    effort: 0,
    id: 948,
    pokemon_id: 158,
    stat_id: 6,
    pokemon_v2_stat: { name: "speed" },
  },
];

export const mocks = [
  {
    request: {
      query: SEARCH_POKEMON,
      variables: { id: -1, name: "Kadabra" },
    },
    result: {
      data: {
        pokemon_v2_pokemon: [
          {
            base_experience: 140,
            height: 13,
            id: 64,
            is_default: true,
            name: "kadabra",
            order: 104,
            pokemon_species_id: 64,
            pokemon_v2_pokemonforms: [
              {
                form_name: "",
                form_order: 1,
                id: 64,
                is_battle_only: false,
                is_default: true,
                is_mega: false,
                name: "kadabra",
                order: 105,
                pokemon_id: 64,
                __typename: "pokemon_v2_pokemonform",
              },
            ],
            weight: 565,
            pokemon_v2_pokemonabilities: [
              {
                ability_id: 28,
                id: 160,
                is_hidden: false,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "synchronize",
                  pokemon_v2_abilityflavortexts: [
                    { id: 1756, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1757, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1758, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1759, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1760, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1761, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1762, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1763, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1764, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1765, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1766, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1767, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1768, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1769, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1770, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1771, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1772, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1773, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1774, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1775, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1776, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1777, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1778, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1779, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1780, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1781, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1782, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1783, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1784, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1785, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1786, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1787, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1788, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1789, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1790, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1791, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1792, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1793, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1794, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1795, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1796, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1797, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1798, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1799, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1800, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1801, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1802, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1803, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1804, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1805, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1806, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1807, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1808, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1809, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1810, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1811, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1812, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1813, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1814, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1815, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1816, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1817, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1818, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1819, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1820, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
              {
                ability_id: 39,
                id: 161,
                is_hidden: false,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "inner-focus",
                  pokemon_v2_abilityflavortexts: [
                    { id: 2471, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2472, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2473, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2474, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2475, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2476, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2477, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2478, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2479, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2480, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2481, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2482, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2483, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2484, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2485, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2486, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2487, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2488, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2489, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2490, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2491, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2492, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2493, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2494, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2495, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2496, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2497, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2498, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2499, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2500, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2501, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2502, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2503, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2504, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2505, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2506, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2507, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2508, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2509, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2510, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2511, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2512, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2513, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2514, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2515, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2516, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2517, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2518, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2519, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2520, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2521, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2522, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2523, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2524, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2525, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2526, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2527, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2528, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2529, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2530, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2531, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2532, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2533, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2534, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2535, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
              {
                ability_id: 98,
                id: 162,
                is_hidden: true,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "magic-guard",
                  pokemon_v2_abilityflavortexts: [
                    { id: 6243, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6244, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6245, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6246, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6247, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6248, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6249, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6250, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6251, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6252, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6253, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6254, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6255, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6256, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6257, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6258, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6259, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6260, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6261, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6262, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6263, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6264, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6265, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6266, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6267, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6268, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6269, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6270, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6271, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6272, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6273, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6274, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6275, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6276, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6277, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6278, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6279, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6280, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6281, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6282, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6283, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6284, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6285, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6286, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6287, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6288, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6289, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6290, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6291, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6292, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6293, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6294, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6295, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6296, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6297, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6298, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6299, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6300, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6301, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6302, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6303, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6304, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
            ],
            pokemon_v2_pokemonstats: [
              {
                base_stat: 40,
                effort: 0,
                id: 379,
                pokemon_id: 64,
                stat_id: 1,
                pokemon_v2_stat: { name: "hp", __typename: "pokemon_v2_stat" },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 35,
                effort: 0,
                id: 380,
                pokemon_id: 64,
                stat_id: 2,
                pokemon_v2_stat: {
                  name: "attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 30,
                effort: 0,
                id: 381,
                pokemon_id: 64,
                stat_id: 3,
                pokemon_v2_stat: {
                  name: "defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 120,
                effort: 2,
                id: 382,
                pokemon_id: 64,
                stat_id: 4,
                pokemon_v2_stat: {
                  name: "special-attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 70,
                effort: 0,
                id: 383,
                pokemon_id: 64,
                stat_id: 5,
                pokemon_v2_stat: {
                  name: "special-defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 105,
                effort: 0,
                id: 384,
                pokemon_id: 64,
                stat_id: 6,
                pokemon_v2_stat: {
                  name: "speed",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
            ],
            pokemon_v2_pokemontypes: [
              {
                pokemon_id: 64,
                pokemon_v2_type: {
                  name: "psychic",
                  pokemon_v2_generation: {
                    name: "generation-i",
                    __typename: "pokemon_v2_generation",
                  },
                  __typename: "pokemon_v2_type",
                },
                __typename: "pokemon_v2_pokemontype",
              },
            ],
            __typename: "pokemon_v2_pokemon",
          },
        ],
      },
    },
  },
  {
    request: {
      query: SEARCH_POKEMON,
      variables: { id: 25, name: "" },
    },
    result: {
      data: {
        pokemon_v2_pokemon: [
          {
            base_experience: 112,
            height: 4,
            id: 25,
            is_default: true,
            name: "pikachu",
            order: 35,
            pokemon_species_id: 25,
            pokemon_v2_pokemonforms: [
              {
                form_name: "",
                form_order: 1,
                id: 25,
                is_battle_only: false,
                is_default: true,
                is_mega: false,
                name: "pikachu",
                order: 36,
                pokemon_id: 25,
                __typename: "pokemon_v2_pokemonform",
              },
            ],
            weight: 60,
            pokemon_v2_pokemonabilities: [
              {
                ability_id: 9,
                id: 54,
                is_hidden: false,
                pokemon_id: 25,
                pokemon_v2_ability: {
                  name: "static",
                  pokemon_v2_abilityflavortexts: [
                    { id: 521, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 522, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 523, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 524, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 525, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 526, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 527, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 528, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 529, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 530, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 531, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 532, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 533, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 534, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 535, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 536, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 537, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 538, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 539, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 540, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 541, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 542, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 543, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 544, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 545, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 546, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 547, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 548, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 549, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 550, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 551, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 552, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 553, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 554, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 555, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 556, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 557, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 558, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 559, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 560, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 561, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 562, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 563, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 564, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 565, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 566, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 567, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 568, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 569, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 570, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 571, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 572, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 573, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 574, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 575, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 576, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 577, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 578, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 579, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 580, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 581, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 582, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 583, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 584, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 585, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
              {
                ability_id: 31,
                id: 55,
                is_hidden: true,
                pokemon_id: 25,
                pokemon_v2_ability: {
                  name: "lightning-rod",
                  pokemon_v2_abilityflavortexts: [
                    { id: 1953, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1954, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1955, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1956, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1951, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1952, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1957, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1958, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1959, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1960, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1961, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1962, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1963, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1964, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1965, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1966, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1967, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1968, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1969, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1970, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1971, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1972, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1973, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1974, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1975, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1976, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1977, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1978, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1979, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1980, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1981, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1982, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1983, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1984, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1985, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1986, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1987, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1988, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1989, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1990, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1991, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1992, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1993, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1994, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1995, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1996, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1997, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1998, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1999, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2000, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2001, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2002, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2003, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2004, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2005, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2006, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2007, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2008, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2009, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2010, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2011, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2012, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2013, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2014, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2015, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
            ],
            pokemon_v2_pokemonstats: [
              {
                base_stat: 35,
                effort: 0,
                id: 145,
                pokemon_id: 25,
                stat_id: 1,
                pokemon_v2_stat: {
                  name: "hp",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 55,
                effort: 0,
                id: 146,
                pokemon_id: 25,
                stat_id: 2,
                pokemon_v2_stat: {
                  name: "attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 40,
                effort: 0,
                id: 147,
                pokemon_id: 25,
                stat_id: 3,
                pokemon_v2_stat: {
                  name: "defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 50,
                effort: 0,
                id: 148,
                pokemon_id: 25,
                stat_id: 4,
                pokemon_v2_stat: {
                  name: "special-attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 50,
                effort: 0,
                id: 149,
                pokemon_id: 25,
                stat_id: 5,
                pokemon_v2_stat: {
                  name: "special-defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 90,
                effort: 2,
                id: 150,
                pokemon_id: 25,
                stat_id: 6,
                pokemon_v2_stat: {
                  name: "speed",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
            ],
            pokemon_v2_pokemontypes: [
              {
                pokemon_id: 25,
                pokemon_v2_type: {
                  name: "electric",
                  pokemon_v2_generation: {
                    name: "generation-i",
                    __typename: "pokemon_v2_generation",
                  },
                  __typename: "pokemon_v2_type",
                },
                __typename: "pokemon_v2_pokemontype",
              },
            ],
            __typename: "pokemon_v2_pokemon",
          },
        ],
      },
    },
  },
  {
    request: {
      query: GET_EVOLUTIONCHAIN,
      variables: { id: 6 },
    },
    result: {
      data: {
        pokemon_v2_evolutionchain: [
          {
            pokemon_v2_pokemonspecies: [
              {
                id: 4,
                pokemon_v2_pokemons: [
                  { name: "charmander", __typename: "pokemon_v2_pokemon" },
                ],
                pokemon_v2_pokemonspeciesflavortexts: [],
                __typename: "pokemon_v2_pokemonspecies",
              },
              {
                id: 5,
                pokemon_v2_pokemons: [
                  { name: "charmeleon", __typename: "pokemon_v2_pokemon" },
                ],
                pokemon_v2_pokemonspeciesflavortexts: [],
                __typename: "pokemon_v2_pokemonspecies",
              },
              {
                id: 6,
                pokemon_v2_pokemons: [
                  { name: "charizard", __typename: "pokemon_v2_pokemon" },
                  {
                    name: "charizard-mega-x",
                    __typename: "pokemon_v2_pokemon",
                  },
                  {
                    name: "charizard-mega-y",
                    __typename: "pokemon_v2_pokemon",
                  },
                  { name: "charizard-gmax", __typename: "pokemon_v2_pokemon" },
                ],
                pokemon_v2_pokemonspeciesflavortexts: [
                  {
                    language_id: 9,
                    flavor_text:
                      "Spits fire that\nis hot enough to\nmelt boulders.\fKnown to cause\nforest fires\nunintentionally.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Spits fire that\nis hot enough to\nmelt boulders.\fKnown to cause\nforest fires\nunintentionally.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "When expelling a\nblast of super\nhot fire, the red\fflame at the tip\nof its tail burns\nmore intensely.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "If CHARIZARD be­\ncomes furious, the\nflame at the tip\fof its tail flares\nup in a whitish-\nblue color.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Breathing intense,\nhot flames, it can\nmelt almost any­\fthing. Its breath\ninflicts terrible\npain on enemies.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It uses its wings\nto fly high. The\ntemperature of its\ffire increases as\nit gains exper­\nience in battle.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "CHARIZARD flies around the sky in\nsearch of powerful opponents.\nIt breathes fire of such great heat\fthat it melts anything. However, it\nnever turns its fiery breath on any\nopponent weaker than itself.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "CHARIZARD flies around the sky in\nsearch of powerful opponents.\nIt breathes fire of such great heat\fthat it melts anything. However, it\nnever turns its fiery breath on any\nopponent weaker than itself.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "A CHARIZARD flies about in search of\nstrong opponents. It breathes intense\nflames that can melt any material. However,\nit will never torch a weaker foe.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Its wings can carry this POKéMON close to\nan altitude of 4,600 feet. It blows out\nfire at very high temperatures.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It spits fire that is hot enough to melt\nboulders. It may cause forest fires by\nblowing flames.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that CHARIZARD’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that CHARIZARD’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that CHARIZARD’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "If CHARIZARD becomes furious,\nthe flame at the tip of its tail flares\nup in a light blue shade.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Breathing intense, hot flames, it can\nmelt almost anything. Its breath\ninflicts terrible pain on enemies.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that Charizard’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that Charizard’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that Charizard’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It is said that Charizard’s fire\nburns hotter if it has\nexperienced harsh battles.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "When expelling a blast of superhot fire,\nthe red flame at the tip of its tail burns\nmore intensely.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Its wings can carry this Pokémon close to an\naltitude of 4,600 feet. It blows out fire at very\nhigh temperatures.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Charizard flies around the sky in search of powerful opponents.\nIt breathes fire of such great heat that it melts anything.\nHowever, it never turns its fiery breath on any opponent\nweaker than itself.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Charizard flies around the sky in search of powerful opponents.\nIt breathes fire of such great heat that it melts anything.\nHowever, it never turns its fiery breath on any opponent\nweaker than itself.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "When this Pokémon expels a blast of superhot\nfire, the red flame at the tip of its tail burns\nmore intensely.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "When this Pokémon expels a blast of superhot\nfire, the red flame at the tip of its tail burns\nmore intensely.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "It spits fire that is hot enough to melt boulders.\nIt may cause forest fires by blowing flames.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                  {
                    language_id: 9,
                    flavor_text:
                      "Its wings can carry this Pokémon close to an\naltitude of 4,600 feet. It blows out fire at very\nhigh temperatures.",
                    __typename: "pokemon_v2_pokemonspeciesflavortext",
                  },
                ],
                __typename: "pokemon_v2_pokemonspecies",
              },
            ],
            id: 2,
            __typename: "pokemon_v2_evolutionchain",
          },
        ],
      },
    },
  },
  {
    request: {
      query: SEARCH_POKEMON,
      variables: { id: 699, name: "" },
    },
    result: {
      data: {
        pokemon_v2_pokemon: [
          {
            base_experience: 140,
            height: 13,
            id: 64,
            is_default: true,
            name: "kadabra",
            order: 104,
            pokemon_species_id: 64,
            pokemon_v2_pokemonforms: [
              {
                form_name: "",
                form_order: 1,
                id: 64,
                is_battle_only: false,
                is_default: true,
                is_mega: false,
                name: "kadabra",
                order: 105,
                pokemon_id: 64,
                __typename: "pokemon_v2_pokemonform",
              },
            ],
            weight: 565,
            pokemon_v2_pokemonabilities: [
              {
                ability_id: 28,
                id: 160,
                is_hidden: false,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "synchronize",
                  pokemon_v2_abilityflavortexts: [
                    { id: 1756, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1757, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1758, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1759, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1760, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1761, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1762, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1763, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1764, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1765, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1766, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1767, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1768, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1769, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1770, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1771, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1772, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1773, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1774, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1775, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1776, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1777, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1778, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1779, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1780, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1781, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1782, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1783, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1784, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1785, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1786, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1787, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1788, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1789, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1790, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1791, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1792, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1793, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1794, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1795, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1796, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1797, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1798, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1799, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1800, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1801, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1802, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1803, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1804, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1805, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1806, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1807, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1808, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1809, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1810, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1811, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1812, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1813, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1814, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1815, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1816, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1817, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1818, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1819, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 1820, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
              {
                ability_id: 39,
                id: 161,
                is_hidden: false,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "inner-focus",
                  pokemon_v2_abilityflavortexts: [
                    { id: 2471, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2472, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2473, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2474, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2475, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2476, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2477, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2478, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2479, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2480, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2481, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2482, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2483, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2484, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2485, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2486, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2487, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2488, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2489, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2490, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2491, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2492, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2493, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2494, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2495, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2496, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2497, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2498, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2499, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2500, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2501, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2502, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2503, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2504, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2505, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2506, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2507, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2508, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2509, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2510, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2511, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2512, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2513, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2514, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2515, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2516, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2517, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2518, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2519, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2520, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2521, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2522, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2523, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2524, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2525, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2526, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2527, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2528, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2529, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2530, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2531, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2532, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2533, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2534, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 2535, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
              {
                ability_id: 98,
                id: 162,
                is_hidden: true,
                pokemon_id: 64,
                pokemon_v2_ability: {
                  name: "magic-guard",
                  pokemon_v2_abilityflavortexts: [
                    { id: 6243, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6244, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6245, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6246, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6247, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6248, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6249, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6250, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6251, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6252, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6253, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6254, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6255, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6256, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6257, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6258, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6259, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6260, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6261, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6262, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6263, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6264, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6265, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6266, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6267, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6268, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6269, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6270, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6271, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6272, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6273, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6274, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6275, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6276, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6277, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6278, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6279, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6280, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6281, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6282, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6283, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6284, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6285, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6286, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6287, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6288, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6289, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6290, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6291, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6292, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6293, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6294, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6295, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6296, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6297, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6298, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6299, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6300, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6301, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6302, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6303, __typename: "pokemon_v2_abilityflavortext" },
                    { id: 6304, __typename: "pokemon_v2_abilityflavortext" },
                  ],
                  __typename: "pokemon_v2_ability",
                },
                __typename: "pokemon_v2_pokemonability",
              },
            ],
            pokemon_v2_pokemonstats: [
              {
                base_stat: 40,
                effort: 0,
                id: 379,
                pokemon_id: 64,
                stat_id: 1,
                pokemon_v2_stat: { name: "hp", __typename: "pokemon_v2_stat" },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 35,
                effort: 0,
                id: 380,
                pokemon_id: 64,
                stat_id: 2,
                pokemon_v2_stat: {
                  name: "attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 30,
                effort: 0,
                id: 381,
                pokemon_id: 64,
                stat_id: 3,
                pokemon_v2_stat: {
                  name: "defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 120,
                effort: 2,
                id: 382,
                pokemon_id: 64,
                stat_id: 4,
                pokemon_v2_stat: {
                  name: "special-attack",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 70,
                effort: 0,
                id: 383,
                pokemon_id: 64,
                stat_id: 5,
                pokemon_v2_stat: {
                  name: "special-defense",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
              {
                base_stat: 105,
                effort: 0,
                id: 384,
                pokemon_id: 64,
                stat_id: 6,
                pokemon_v2_stat: {
                  name: "speed",
                  __typename: "pokemon_v2_stat",
                },
                __typename: "pokemon_v2_pokemonstat",
              },
            ],
            pokemon_v2_pokemontypes: [
              {
                pokemon_id: 64,
                pokemon_v2_type: {
                  name: "psychic",
                  pokemon_v2_generation: {
                    name: "generation-i",
                    __typename: "pokemon_v2_generation",
                  },
                  __typename: "pokemon_v2_type",
                },
                __typename: "pokemon_v2_pokemontype",
              },
            ],
            __typename: "pokemon_v2_pokemon",
          },
        ],
      },
    },
  },
];
